services:
  - docker

before_install:
  - docker build -t wilo17/docker-react -f Dockerfile.dev .

script:
  - docker run wilo17/docker-react npm run test -- --coverage

deloy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-564465465464"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
